---
# Install core packages for my devenv.
- name: Install basic dev tools
  hosts: localhost
  connection: local
  become: true
  vars:
    - bin_dir: "/usr/bin"
  tasks:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: true
        autoremove: true
    - name: Install LLVM 11 toolchain
      package:
        name:
          - llvm-11
          - clang-format-11
          - clang-tools-11
          - clang-tidy-11
          - clang-11
          - clangd-11
        state: present
    - name: Setup LLVM symlinks
      file:
        src: "{{ bin_dir }}/{{ item }}-11"
        dest: "{{ bin_dir }}/{{ item }}"
        state: link
      loop:
        - "clang-format"
        - "clang-tidy"
        - "clang"
        - "clangd"
        - "run-clang-tidy"
    - name: Install generic tools
      package:
        name:
          - build-essential  # ...
          - bear  # Makefile -> compile_database.json
          - git  # ...
          - gawk  # GNU awk
          - fzf  # Fuzzy finder
          - fuse3  # Support appimages
          - openssh-client  # ...
          - openssh-server  # ...
        state: present
    - name: Install GCC toolchain
      package:
        name:
          - gcc-10-multilib
          - g++-10-multilib
        state: present
    - name: Setup GCC symlinks
      file:
        src: "{{ bin_dir }}/{{ item }}-10"
        dest: "{{ bin_dir }}/{{ item }}"
        state: link
      loop:
        - "gcc"
        - "g++"
    - name: Python development tools
      pip:
        name:
          - pynvim  # For neovim
          - compiledb  # bear alternative
          - poetry  # Package management
          - black  # Formatter
          - isort  # Sort imports
          - flake8  # Diagnostics
          - pyright  # Diagnostics
          - pylint  # Diagnostics
          - yamllint  # Diagnostics
          - ansible-lint  # Diagnostics
        state: present
    - name: Autoremove all unneeded packages
      apt:
        autoclean: true
    - name: Autoclean all unneeded packages
      apt:
        autoremove: true
