---
# Install core packages for my devenv.
- name: Install basic dev tools
  hosts: localhost
  connection: local
  become: true
  vars:
    bin_dir: "/usr/bin"
    LLVM_version: "19"
    GCC_version: "14"
  tasks:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: true
        autoremove: true
    - name: Install LLVM {{ LLVM_version }} toolchain
      package:
        name:
          - llvm-{{ LLVM_version }}
          - clang-format-{{ LLVM_version }}
          - clang-tools-{{ LLVM_version }}
          - clang-tidy-{{ LLVM_version }}
          - clang-{{ LLVM_version }}
          - clangd-{{ LLVM_version }}
        state: present
    - name: Setup LLVM symlinks
      file:
        src: "{{ bin_dir }}/{{ item }}-{{ LLVM_version }}"
        dest: "{{ bin_dir }}/{{ item }}"
        state: link
      loop:
        - "clang-format"
        - "clang-tidy"
        - "clang"
        - "clangd"
        - "run-clang-tidy"
    - name: Install generic tools
      package:
        name:
          - build-essential  # ...
          - git  # ...
          - gawk  # GNU awk
          - ripgrep  # ripgrep, used by fzf
          - fuse3  # Support appimages
          - codespell  # Spellcheck in neovim
          - openssh-client  # ...
          - openssh-server  # ...
          - zip
          - unzip
          - cmake
          - gettext # For neovim
          - curl
          - wget
          - bsdmainutils # for colrm
        state: present
    - name: Install GCC toolchain
      package:
        name:
          - gcc-{{ GCC_version }}
          - g++-{{ GCC_version }}
        state: present
    - name: Setup GCC symlinks
      file:
        src: "{{ bin_dir }}/{{ item }}-{{ GCC_version }}"
        dest: "{{ bin_dir }}/{{ item }}"
        state: link
      loop:
        - "gcc"
        - "g++"
    - name: install fzf
      become: false
      shell: (git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf || true) && ~/.fzf/install
    - name: Python development tools
      pip:
        name:
          - pynvim  # For neovim
          - compiledb  # bear alternative
          - ruff  # Diagnostic
          - yamllint  # Diagnostics
          - ansible-lint  # Diagnostics
          - mdformat  # Markdown formatter
          - uv
        state: present
        extra_args: "--break-system-packages"
    - name: Autoremove all unneeded packages
      apt:
        autoclean: true
    - name: Autoclean all unneeded packages
      apt:
        autoremove: true
