---
# Install core packages for my devenv.
- name: Install basic dev tools
  hosts: localhost
  connection: local
  become: true
  vars:
    - bin_dir: "/usr/bin"
  tasks:
    - name: Update packages
      apt:
        update_cache: true
        upgrade: true
        autoremove: true
    - name: Install LLVM 13 toolchain
      package:
        name:
          - llvm-13
          - clang-format-13
          - clang-tools-13
          - clang-tidy-13
          - clang-13
          - clangd-13
        state: present
    - name: Setup LLVM symlinks
      file:
        src: "{{ bin_dir }}/{{ item }}-13"
        dest: "{{ bin_dir }}/{{ item }}"
        state: link
      loop:
        - "clang-format"
        - "clang-tidy"
        - "clang"
        - "clangd"
        - "run-clang-tidy"
    - name: Install generic tools
      package:
        name:
          - build-essential  # ...
          - git  # ...
          - gawk  # GNU awk
          - ripgrep  # ripgrep, used by fzf
          - fzf  # Fuzzy finder
          - fuse3  # Support appimages
          - codespell  # Spellcheck in neovim
          - openssh-client  # ...
          - openssh-server  # ...
          - zip
        state: present
    - name: Install GCC toolchain
      package:
        name:
          - gcc-10
          - g++-10
        state: present
    - name: Setup GCC symlinks
      file:
        src: "{{ bin_dir }}/{{ item }}-10"
        dest: "{{ bin_dir }}/{{ item }}"
        state: link
      loop:
        - "gcc"
        - "g++"
    - name: Python development tools
      pip:
        name:
          - pynvim  # For neovim
          - compiledb  # bear alternative
          - poetry  # Package management
          - black  # Formatter
          - isort  # Sort imports
          - flake8  # Diagnostics
          - pyright  # Diagnostics
          - pylint  # Diagnostics
          - pydocstyle  # Diagnostics
          - yamllint  # Diagnostics
          - ansible-lint  # Diagnostics
        state: present
    - name: Download stylua
      get_url:
        url: "https://github.com/JohnnyMorganz/StyLua/releases/download/v0.12.5/stylua-0.12.5-linux.zip"
        dest: "/tmp/stylua.zip"
    - name: Install stylua
      unarchive:
        src: "/tmp/stylua.zip"
        dest: "{{ bin_dir}}"
        mode: 0711
    - name: Autoremove all unneeded packages
      apt:
        autoclean: true
    - name: Autoclean all unneeded packages
      apt:
        autoremove: true
