---
- name: Install neovim
  hosts: localhost
  vars:
    - user_home: "{{ ansible_env.HOME }}"
    - user: "{{ ansible_env.USER }}"
  connection: local
  tasks:
    - name: Create local bin directories
      file:
        path: "{{ user_home }}/.local/bin"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
    - name: Neovim prerequisities
      package:
        name:
          - liblua5.1-dev
          - luajit
          - libluajit-5.1-dev
          - libperl-dev
          - libncurses5-dev
          - ruby-dev
          - fuse3
        state: present
    - name: Download latest app image
      get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
        dest: "{{ user_home }}/.local/bin/nvim"
        mode: '0711'
